services:
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=tiktakdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

volumes:
  postgres_data:

