server:
  port: 8181
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/tiktakdb}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}
    dbcp2:
      validation-query: select 1
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true  # Added this line
        generate_statistics: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
  docker:
    compose:
      lifecycle-management: start-only

image:
  set:
    minCount: 1
    maxCount: 3




